spring:
  autoconfigure:
    exclude:
#      - org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration
  application:
    name: etesterdb2
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/rulefree
    username: rulefree_user
    password: rulefree_user

  jpa.show-sql: true
#  jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  hibernate.ddl-auto: update

#  security:
#    user:
#      name: sesi
#      password: admin

# App Properties
etester.app:
  jwtCookieName: etester
# jwtSecret needs to be big in size.  When I used a secret of 'EtesterSecretKey', I get this error "The signing key's size is 96 bits which is not secure enough for the HS512 algorithm" 
# I icreased it to 'EtesterSecretKeyEashwarPooja3311' and multiplied by 3
  jwtSecret: EtesterSecretKeyEashwarPooja3311EtesterSecretKeyEashwarPooja3311EtesterSecretKeyEashwarPooja3311
  jwtExpiration: 86400

server:
  port : 8081

logging:
  level:
    org:
      springframework:
        security: debug
    com.etester:
      security: trace
      data: debug
