spring:
  autoconfigure:
    exclude:
#      - org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration
  application:
    name: etesterdb2
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/rulefree
    username: rulefree_user
    password: rulefree_user

  jpa.show-sql: true
  jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  hibernate.ddl-auto: update

#  security:
#    user:
#      name: sesi
#      password: admin

# App Properties
etester.app:
  jwtCookieName: etester
  jwtSecret: EtesterSecretKey
  jwtExpiration: 86400

server:
  port : 8081

logging:
  level:
    org:
      springframework:
        security: debug
    com.etester:
      security: trace
      data: debug
